get:
  description: List all collections
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/collections-list.json
          schema: !include ../schemas/output/collection-list.json
